### PR TITLE
PR ready RTD/Irradiance Sensor Board. Added extra mounts for irradian…

### PR DESCRIPTION
**Pull request by dimembermatt**
…ce I2C and updated power reg to match MPPT. Also cleaner layout.

# Quality Assurance Checklist
To make reviews more efficient, please make sure the board meets the following standards and check everything off once the board meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.

### Minimum Prerequisites
- [X] Pushed changes to branch.
- [X] The board passes ERC and DRC.
    - Note some ERC warnings are acceptable.
- [X] All traces are routed.
- [X] Units are in metric.

### 2D Spacing
- [X] The components are spaced out at an optimal distance.
    - All components can be easily hand-soldered.
    - IPC-SM-782A Standard requires a minimum distance of 1.0mm from edge to edge.
- [X] Components that are in parallel with each other are spaced out at an equal distance when possible.
- [X] The components are aligned with each other when possible.
- [X] Components are grouped based off of functionality.
    - E.g. all components for CAN should be grouped.
- [X] Bypass capacitors are less than 1cm away from their respective IC's power pins.

### 3D Spacing
- [X] Layout of components have been placed with mounting location and usage of the board in mind.
    - Are PCBs going to be stacked on above/below this board? Are tall components placed accordingly?
    - Are buttons and lights easily accessible and viewable?
    - When mounted into the car, are the heights of the components and connectors accounted for?
- [X] Location of connectors and wires going out of the board will prevent messy wiring.
    - Are all the wires that are going in the same direction placed on the same edge of the board?

### Components
- [X] Custom footprints have been double checked with the datasheet.
- [X] Pin 1 of the footprint is labeled in some way.

### Copper Layer
- [X] The trace widths and trace clearances are greater than JLCPCB's minimum requirements.
- [X] The trace lengths are as short as possible.
    - Can there be a more optimal route if you go to another layer?
- [X] Each trace's width is capable of handling the expected current flow.
    - Use PCB width calculator to calculate trace width.
- [X] *No sharp corners. No trace angles equal to or less than 90 degrees.
- [X] Traces are in parallel with each other when possible.
    - E.g. traces connected between an IC and MCU can be placed in parallel with each other.
- [X] There are no random trace appendages.
- [X] Vias placed in copper pads are fully encompassed in the copper pads.
- [X] Through-hole components do not have extraneous vias.

*Not really a problem for modern manufacturing techniques but good practice and important for high speed signal integrity.

### Silkscreen Layer
- [X] Visible text sizes are greater than JLCPCB's minimum requirements.
- [X] All visible text is on the silkscreen layer.
- [X] All reference labels of each component are not overlapping a copper pad or another component.
- [X] All connector pins are labeled with a meaningful and helpful name.
- [X] All LEDs are labeled with a meaningful and helpful name.

### Edge Cut Layer
- [X] The dimensions of the board and the mounting holes are nice values in metric i.e. no long decimals.
- [X] The physical outline of the board is on the edge cut layer.
- [X] Edge cuts are straight and parallel with opposite edge of the board.
- [X] Mounting holes are aligned.
- [X] Corners are curved and contoured to mounting holes.

### IMPORTANT NOTICE
- [X] I am confident that this board will be safe to use in a safety critical environment.
- [X] I had fun :)

## Other Comments
_Write any comments about the board that would help the reviewers here._

### CODE REVIEW

**Comment by chaseblock** [comment]
J1 and J2 seem a bit close to J5 on the layout. Might be good to space them another mm apart.

**Comment by chaseblock** [comment]
Actually, looking at the 3D model, it's probably fine. I don't see anything concerning.

**Comment by HannahSLee14** [comment]
On the schematic: 

1. I know this doesn't affect the wiring at all, but for future purposes, if any member is looking at the board, can you make SDO and DRDY hierarchical labels outputs rather than inputs? This way, people in the future can look at it and understand the direction of the data flow at first glance. 

2. This also doesn't affect the wiring of anything, but it might be good to leave a note somewhere that GNDPWR = GND and GNDREF = GNDPWR (or noting that this board does something like that since it differs from most of the other boards on the other team in case someone gets confused about it in the future). 

On the PCB: 

1. Is there a reason why the trace length of 3.3V suddenly changes here? 
image

2. On each RTD connection, is there a reason why both GNDPWR pins need vias to the other side if they're already connected to each other? 
image

3. This is super small, but just in case you wanted it to be straight (if you're fine with it the way it is, you can ignore me!), there is a slight squiggle in the SDO trace on the back side on the left side of the Nucleo. 
image

4. This is just personal preference but you can make the mounting hole silkscreen labels invisible if you want since we don't need it. It doesn't really change anything though, one way or the other. 

5. Also, the naming convention of the other boards is like: UTSVT - Array (on the first line), RTD Board v1.0 (on the second line), Fall 2020 (on the third line), and then any names after that. It doesn't change the layout much, but it might be nice to standardize the boards so they all have the same naming system. 

Other than those small things, it looks like a really nice board! I like how symmetrical and neat everything is laid out.

**Comment by dimembermatt** [comment]
@HannahSLee14 

Schematic #2, according to Professor Hallock, this seems to be a remnant from a bunch of other boards. Has this been corrected system wide by now such that GNDREF -> device and GNDPWR -> car?

Layout #1: This was a remnant of the 3V/5V lines coming out from CAN. I'll change those to .5mm tracks.
Layout #2: This was something I learned from this [guy](https://www.youtube.com/watch?v=v8seW2BZits&list=PLXvLToQzgzdeMHns7IIdK0XFwNt9LSoxo), having a gnd/pwr via for every pad. It won't kill anybody if it's connected to the same via, it was just supposed to be a "do this until you have no other option" thing.

**Comment by HannahSLee14** [comment]
At least for the boards that I have seen, it's now GNDPWR -> car and GND -> device. 

And oh cool! I didn't know that. I'll take a look at the video.

**Comment by dimembermatt** [comment]
Yeah, he's super cool, I've been watching a lot of his videos and EEV blog's videos since fall break.

**Pull request merged**
